# Generated by Django 6.0.2 on 2026-02-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='approver_required',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='camera_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='visitor',
            name='capture_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='capture_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='captured_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='visitor',
            name='captured_photo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='cnic_passport',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='visitor',
            name='department_for_slot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='face_match_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='guard_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host_full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='ntn_registration_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visitor',
            name='organization_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='photo_quality_score',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='preferred_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='preferred_time_slot_walkin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='registration_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='slot_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='temporary_access_granted',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_purpose_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='watchlist_check_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
