# Generated by Django 6.0.2 on 2026-02-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_approver_required_visitor_camera_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='additional_document',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='application_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='back_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='captured_photo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='front_image',
            field=models.TextField(blank=True),
        ),
    ]
