# Generated by Django 5.2.11 on 2026-05-02 07:04

import detentions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentionmemo',
            name='driver_photo_upload',
            field=models.FileField(blank=True, null=True, upload_to=detentions.models.detention_driver_photo_path),
        ),
        migrations.AddField(
            model_name='detentionmemo',
            name='owner_photo_upload',
            field=models.FileField(blank=True, null=True, upload_to=detentions.models.detention_owner_photo_path),
        ),
        migrations.CreateModel(
            name='DetentionMemoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to=detentions.models.detention_attachment_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
