# Generated by Django 5.2.11 on 2026-05-02 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentions', '0002_detentionmemo_driver_photo_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccountEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treasury_challan_no', models.CharField(blank=True, max_length=120)),
                ('deposit_type', models.CharField(blank=True, max_length=80)),
                ('case_seizure_ref', models.CharField(blank=True, max_length=200)),
                ('fir_no', models.CharField(blank=True, max_length=120)),
                ('customs_station', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=120)),
                ('deposit_date', models.CharField(blank=True, max_length=40)),
                ('bank_treasury_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detention_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_entries', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
