# Generated by Django 5.2.11 on 2026-05-05 11:40

import detentions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentions', '0003_depositaccountentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetentionMemoGoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=detentions.models.detention_goods_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('goods_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='detentions.detentionmemogoodsline')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
