# Generated by Django 5.2.11 on 2026-07-11 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentions', '0004_repair_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentionmemo',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='DetentionMemoAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('media_added', 'Media added')], db_index=True, max_length=40)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='detentions.detentionmemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
