# Generated by Django 5.2.11 on 2026-07-11 11:55

import detentions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentions', '0005_detentionmemo_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detentionmemo',
            name='driver_photo_upload',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=detentions.models.detention_driver_photo_path),
        ),
        migrations.AlterField(
            model_name='detentionmemo',
            name='owner_photo_upload',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=detentions.models.detention_owner_photo_path),
        ),
        migrations.AlterField(
            model_name='detentionmemoattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=detentions.models.detention_attachment_path),
        ),
        migrations.AlterField(
            model_name='detentionmemogoodsimage',
            name='image',
            field=models.FileField(max_length=500, upload_to=detentions.models.detention_goods_image_path),
        ),
    ]
